# Generated by Django 6.0.6 on 2026-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', '🟡 Applied'), ('Shortlisted', '🔵 Shortlisted'), ('Interview', '🟠 Interview Scheduled'), ('Offer', '🟢 Offer Received'), ('Rejected', '🔴 Rejected'), ('Withdrawn', '⚪ Withdrawn')], default='Applied', max_length=20),
        ),
    ]
