# Generated by Django 6.0.6 on 2026-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
