# Generated by Django 6.0.6 on 2026-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
