# Generated by Django 6.0.6 on 2026-07-20 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_preparationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='provider',
            field=models.CharField(default='Adzuna', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='provider_job_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(default='Adzuna', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['provider_job_id'], name='jobs_job_provide_6f85c7_idx'),
        ),
    ]
