# Generated by Django 6.0.6 on 2026-07-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_fetched_at_job_is_active_job_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
