# Generated by Django 6.0.6 on 2026-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('interview_rounds', models.TextField()),
                ('required_skills', models.TextField()),
                ('preparation_tips', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
