# Generated by Django 6.0.6 on 2026-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='job_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='resume_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
