# Generated by Django 6.0.6 on 2026-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
