# Generated by Django 6.0.6 on 2026-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resumes.skill'),
        ),
    ]
