# Generated by Django 6.0.6 on 2026-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_year_studentprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
