# Generated by Django 6.0.6 on 2026-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ai_career_recommendations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ai_job_matching',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ai_resume_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'తెలుగు'), ('hi', 'हिन्दी')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_visibility',
            field=models.CharField(choices=[('private', 'Private'), ('recruiters', 'Recruiters Only'), ('public', 'Public')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_visibility',
            field=models.CharField(choices=[('private', 'Private'), ('recruiters', 'Recruiters Only'), ('public', 'Public')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='smart_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', 'India'), ('UTC', 'UTC')], default='Asia/Kolkata', max_length=50),
        ),
    ]
