# Generated by Django 6.0.6 on 2026-07-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofile_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interview_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='job_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weekly_report',
            field=models.BooleanField(default=True),
        ),
    ]
