# Generated by Django 6.0.6 on 2026-07-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_coverletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoverLetter',
        ),
    ]
